services:
  secret-note-db:
    image: postgres
    volumes:
      - ./data/secret-note-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=secretnote
      - POSTGRES_USER=secretnote
      - POSTGRES_PASSWORD=secretnote
      - POSTGRES_HOST=secret-note-db
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgres://secretnote:secretnote@secret-note-db:5432/secretnote

  web:
    build: .
    command: >
      sh -c "until nc -z secret-note-db 5432; do echo waiting for secret-note-db; sleep 1; done &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              gunicorn secret_notes_project.wsgi:application --bind 0.0.0.0:8008"
    volumes:
      - .:/app
    ports:
      - "8008:8008"
    environment:
      - DATABASE_URL=postgres://secretnote:secretnote@secret-note-db:5432/secretnote
      - DEBUG=False
    depends_on:
      - secret-note-db

volumes:
  static_volume:
