apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-note-config
data:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_HOST: {{ .Values.database.host | quote }}
  POSTGRES_PORT: {{ .Values.database.port | quote }}
  DATABASE_URL: {{ .Values.database.url | quote }}
  DEBUG: {{ .Values.debug | quote }}
