apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secret-note-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}
