apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-note
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: secret-note
  template:
    metadata:
      labels:
        app: secret-note
    spec:
      containers:
        - name: secret-note
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8008
          envFrom:
            - configMapRef:
                name: secret-note-config
            - secretRef:
                name: secret-note-secret
          env:
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
          command: ["gunicorn", "secret_notes_project.wsgi:application", "--bind", "0.0.0.0:8008"]

      initContainers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: secret-note-config
            - secretRef:
                name: secret-note-secret
          env:
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
          command: ["python", "manage.py", "migrate"]
