apiVersion: v1
kind: Service
metadata:
  name: secret-note
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8008
  selector:
    app: secret-note
